/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem.studentregistration;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import studentmanagementsystem.dbconnect;

/**
 *
 * @author dess
 */
public class alterstudentdetails extends javax.swing.JInternalFrame {

    public alterstudentdetails() {
        initComponents();
        display();
    }
    public ArrayList<registeredstudents>getRegisteredstudents()
{
    ArrayList<registeredstudents> studentslist=new ArrayList<registeredstudents>();
    Connection connection=dbconnect.ConnectDB();
    String query="SELECT * FROM student_registration";
    Statement pst;
    ResultSet rst;
    
    try{
        pst=connection.createStatement();
        rst=pst.executeQuery(query);
        
        registeredstudents student;
        while(rst.next())
        {
            student=new registeredstudents(rst.getString("student_id"),rst.getString("student_name"),rst.getString("dob"),rst.getString("doa"),rst.getString("contact_address"),rst.getString("gender"),rst.getString("parent_name"));
            studentslist.add(student);
        }
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
    return studentslist;
}
     public void display()
{
    ArrayList<registeredstudents> list=getRegisteredstudents();
    DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
    Object[]row=new Object[7];
    for(int i=0;i<list.size();i++)
    {
        row[0]=list.get(i).getid();
        row[1]=list.get(i).getname();
        row[2]=list.get(i).getdob();
        row[3]=list.get(i).getdoa();
        row[4]=list.get(i).getcontact();
        row[5]=list.get(i).getgender();
        row[6]=list.get(i).getparent();
        model.addRow(row);
    }
}
     public void executeQuery(String query,String message)
{
    Connection con=dbconnect.ConnectDB();
    Statement st;
    try
    {
        st=con.createStatement();
        if((st.executeUpdate(query)) ==1)
        {
            //refresh table
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            display();
            
            JOptionPane.showMessageDialog(null, "Data"+message+"Successfully");
        }
        else{
            JOptionPane.showMessageDialog(null, "Data Not"+message);
        }
        
    }
    catch(Exception ex){
        ex.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jparentname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcombogender = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jcontactaddress = new javax.swing.JTextField();
        jdoa = new javax.swing.JTextField();
        jdob = new javax.swing.JTextField();
        jstudentname = new javax.swing.JTextField();
        jstudentid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Alter Student Details");

        jLabel3.setText("Date of Birth");

        jLabel4.setText("Date of Admission");

        jLabel1.setText("Student ID");

        jLabel5.setText("Contact Address");

        jLabel6.setText("Gender");

        jcombogender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel7.setText("Guardian/Parent Name");

        jstudentid.setEditable(false);
        jstudentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jstudentidActionPerformed(evt);
            }
        });

        jLabel2.setText("Student Name");

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "student id", "student name", "date of birth", "date of admission", "contact", "gender", "parent name"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7))
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdob)
                    .addComponent(jstudentname)
                    .addComponent(jstudentid)
                    .addComponent(jcombogender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcontactaddress)
                    .addComponent(jdoa)
                    .addComponent(jparentname)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jstudentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jstudentname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jdoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcontactaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcombogender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jparentname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(4, 4, 4)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jstudentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jstudentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jstudentidActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jstudentid.setText("");
        jstudentname.setText("");
        jdob.setText("");
        jdoa.setText("");
        jcontactaddress.setText("");
        jparentname.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        //get the index of the selected row
        int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        jstudentid.setText(model.getValueAt(i, 0).toString());
        jstudentname.setText(model.getValueAt(i, 1).toString());
        jdob.setText(model.getValueAt(i, 2).toString());
        jdoa.setText(model.getValueAt(i, 3).toString());
        jcontactaddress.setText(model.getValueAt(i, 4).toString());
        jcombogender.setSelectedItem(model.getValueAt(i, 5).toString());
        jparentname.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         //update
        String query="UPDATE sms.student_registration SET student_id='"+jstudentid.getText()+"',"
                + "student_name='"+jstudentname.getText()+"', dob='"+jdob.getText()+"',"
        + "doa='"+jdoa.getText()+"',contact_address='"+jcontactaddress.getText()+"',"
                + "gender='"+jcombogender.getSelectedItem()+"',"
                + "parent_name='"+jparentname.getText()+"'"
        + "WHERE student_id="+jstudentid.getText();
        executeQuery(query,"Updated");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String query="DELETE FROM sms.student_registration WHERE student_id="+jstudentid.getText();
        executeQuery(query,"Data Deleted");
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcombogender;
    private javax.swing.JTextField jcontactaddress;
    private javax.swing.JTextField jdoa;
    private javax.swing.JTextField jdob;
    private javax.swing.JTextField jparentname;
    private javax.swing.JTextField jstudentid;
    private javax.swing.JTextField jstudentname;
    // End of variables declaration//GEN-END:variables
}
