
package studentmanagementsystem.studentregistration;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dess
 */
public class viewregisteredstudents extends javax.swing.JInternalFrame {

    public viewregisteredstudents() {
        initComponents();
        display();
    }
       public Connection getConnection()
{
Connection con;
try{
  con=DriverManager.getConnection("jdbc:mysql://localhost:3306/sms","root","kimutai2014");
return con;
}
catch(Exception e)
{
e.printStackTrace();
return null;
}
}
    public ArrayList<registeredstudents>getRegisteredstudents()
{
    ArrayList<registeredstudents> studentslist=new ArrayList<registeredstudents>();
    Connection connection=getConnection();
    String query="SELECT * FROM student_registration";
    Statement pst;
    ResultSet rst;
    
    try{
        pst=connection.createStatement();
        rst=pst.executeQuery(query);
        
        registeredstudents student;
        while(rst.next())
        {
            student=new registeredstudents(rst.getString("student_id"),rst.getString("student_name"),rst.getString("dob"),rst.getString("doa"),rst.getString("contact_address"),rst.getString("gender"),rst.getString("parent_name"));
            studentslist.add(student);
        }
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
    return studentslist;
}
     public void display()
{
    ArrayList<registeredstudents> list=getRegisteredstudents();
    DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
    Object[]row=new Object[7];
    for(int i=0;i<list.size();i++)
    {
        row[0]=list.get(i).getid();
        row[1]=list.get(i).getname();
        row[2]=list.get(i).getdob();
        row[3]=list.get(i).getdoa();
        row[4]=list.get(i).getcontact();
        row[5]=list.get(i).getgender();
        row[6]=list.get(i).getparent();
        model.addRow(row);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registered Students");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Date of Birth", "Date of Admission", "Contact Address", "Gender", "Parent/Guardian Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            display();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
