/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem.studentperformance;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import studentmanagementsystem.dbconnect;


/**
 *
 * @author dess
 */
public class exam_entry extends javax.swing.JInternalFrame {
PreparedStatement pst=null;
Connection conn=null;
ResultSet rs=null;
    /**
     * Creates new form exam_entry
     */
    public exam_entry() {
        initComponents();
        fillcombo();
        display();
    }
    public ArrayList<examsclass>getstudentperformance()
{
    ArrayList<examsclass> studentslist=new ArrayList<examsclass>();
    Connection connection=dbconnect.ConnectDB();
    String query="SELECT * FROM student_performance";
    Statement pst;
    ResultSet rst;
    
    try{
        pst=connection.createStatement();
        rst=pst.executeQuery(query);
        
        examsclass student;
        while(rst.next())
        {
            student=new examsclass(rst.getString("registration_id"),rst.getString("cat1"),rst.getString("cat2"),rst.getString("exam"),rst.getString("total"),rst.getString("grade"));
            studentslist.add(student);
        }
    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
    return studentslist;
}
    public void display()
{
    ArrayList<examsclass> list=getstudentperformance();
    DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
    Object[]row=new Object[6];
    for(int i=0;i<list.size();i++)
    {
        row[0]=list.get(i).getid();
        row[1]=list.get(i).getcat1();
        row[2]=list.get(i).getcat2();
        row[3]=list.get(i).getexam();
        row[4]=list.get(i).gettotal();
        row[5]=list.get(i).getgrade();
        model.addRow(row);
    }
}
 public void executeQuery(String query,String message)
{
    Connection conn=dbconnect.ConnectDB();
    Statement st;
    try
    {
        st=conn.createStatement();
        if((st.executeUpdate(query)) ==1)
        {
            //refresh table
            DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            display();
            JOptionPane.showMessageDialog(null, "Data"+message+"Successfully");
        }
        else{
            JOptionPane.showMessageDialog(null, "Data Not"+message);
        }
        
    }
    catch(Exception ex){
        ex.printStackTrace();
    }
}
    private void fillcombo()
    {
        conn=dbconnect.ConnectDB();
        
        try
        {
          String sql="select * from student_course_registration";
          pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
          
          while(rs.next())
          {
              String name=rs.getString("student_id");
              jregistrationid.addItem(name);
          }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }

  /* private void fillcourses()
    {
        conn=dbconnect.ConnectDB();
        
        try
        {
          String query="select * from student_course_registration";
          pst=conn.prepareStatement(query);
          rs=pst.executeQuery();
          
          while(rs.next())
          {
              String name=rs.getString("course_name");
              jcoursename.addItem(name);
          }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcat1 = new javax.swing.JTextField();
        jcat2 = new javax.swing.JTextField();
        jexam = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jregistrationid = new javax.swing.JComboBox<>();
        jstudentname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcoursename = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("Exams Entry");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration Id", "CAT1", "CAT2", "Exam", "Total", "Grade"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Registration Id");

        jLabel2.setText("CAT1");

        jLabel3.setText("CAT2");

        jLabel4.setText("Exam");

        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jregistrationid.setToolTipText("");
        jregistrationid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jregistrationidItemStateChanged(evt);
            }
        });
        jregistrationid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jregistrationidMouseClicked(evt);
            }
        });
        jregistrationid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jregistrationidActionPerformed(evt);
            }
        });

        jLabel5.setText("Course Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jstudentname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcat1)
                            .addComponent(jcat2)
                            .addComponent(jexam)
                            .addComponent(jregistrationid, 0, 94, Short.MAX_VALUE)
                            .addComponent(jcoursename, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(29, 29, 29)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jregistrationid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcoursename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jexam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jstudentname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jregistrationidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jregistrationidActionPerformed
    //fillcourses(); 
// TODO add your handling code here:
    
    }//GEN-LAST:event_jregistrationidActionPerformed

    private void jregistrationidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jregistrationidMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jregistrationidMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jcat1.getText().equals("")||jcat2.getText().equals("")||jexam.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Enter Respective Scores");
        }
        else if(Integer.parseInt(jcat1.getText())>30||Integer.parseInt(jcat2.getText())>30||Integer.parseInt(jexam.getText())>70)
                {
                    JOptionPane.showMessageDialog(null,"Enter Correct Marks.\n CATs=<30\n Exams =<70");
                }
        else{
        double Total;
        String Grade;
        Total=Integer.parseInt(jcat1.getText())+Integer.parseInt(jcat2.getText())+Integer.parseInt(jexam.getText());
        if(Total>69)
        {
            Grade="A";
        }
        else if(Total>59)
                {
                  Grade="B";
                }
        else if(Total>49)
                {
                  Grade="C";
                }
        else if(Total>39)
                {
                  Grade="D";
                }
        else
                {
                  Grade="E";
                }
        String query="INSERT INTO sms.student_performance(registration_id, cat1, cat2, exam, total, grade) values"
        + "('"+jregistrationid.getSelectedItem()+"',"
        + "'"+jcat1.getText()+"',"
        + "'"+jcat2.getText()+"',"
        + "'"+jexam.getText()+"','"+Total+"','"+Grade+"')";
        executeQuery(query, "inserted");
        jcat1.setText("");
        jcat2.setText("");
        jexam.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jregistrationidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jregistrationidItemStateChanged
        // TODO add your handling code here:
       
       /*  try{
        Connection conn=dbconnect.ConnectDB();
        String query="select * from student_course_registration where student_id='"+jregistrationid.getSelectedItem()+"'";
          pst=conn.prepareStatement(query);
          rs=pst.executeQuery();
                 
          while(rs.next())
          {
              String name=rs.getString("course_name");
              jcoursename.addItem(name);
          }
       }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);*/
    }//GEN-LAST:event_jregistrationidItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jcat1;
    private javax.swing.JTextField jcat2;
    private javax.swing.JComboBox<String> jcoursename;
    private javax.swing.JTextField jexam;
    private javax.swing.JComboBox<String> jregistrationid;
    private javax.swing.JLabel jstudentname;
    // End of variables declaration//GEN-END:variables
}
